name: Build and Release Images
  
on: workflow_dispatch

jobs:
  build-release:
    runs-on: ubuntu-latest
    env: 
      AUTH0_DOMAIN: scribe-hub-dev.us.auth0.com
      AUTH0_SCRIBE_SERVICE_AUDIENCE: api.research.scribesecurity.com
      SCRIBE_API_BASE_URI: https://airflow.research.scribesecurity.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate cyclonedx json SBOM for git repo
        uses: scribe-security/action-bom@master
        with:
          type: git
          target: .
          format: json
          product-key: airflow-git-SBOM
          product-version: ${{ github.run_id }}
          scribe-enable: true
          scribe-url: $SCRIBE_API_BASE_URI
          scribe-login-url: https://$AUTH0_DOMAIN
          scribe-auth-audience: $AUTH0_SCRIBE_SERVICE_AUDIENCE
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build images
        run: |
          docker build -t airflow-image:${{ github.sha }} .

      - name: Display Docker image
        run: docker images

      - name: Generate cyclonedx json SBOM for docker image
        uses: scribe-security/action-bom@master
        with:
          type: docker
          target: 'airflow-image:${{ github.sha }}'
          format: json
          force: true
          product-key: airflow-image-SBOM
          product-version: ${{ github.run_id }}
          scribe-enable: true
          scribe-url: $SCRIBE_API_BASE_URI
          scribe-login-url: https://$AUTH0_DOMAIN
          scribe-auth-audience: $AUTH0_SCRIBE_SERVICE_AUDIENCE
          scribe-client-id: ${{ secrets.clientid }}
          scribe-client-secret: ${{ secrets.clientsecret }}

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag airflow-image:${{ github.sha }} shivamkush/airflow:latest

      - name: Push Docker image to Docker Hub
        run: docker push shivamkush/airflow:latest
